[package]
name = "ustar"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
bitbybit = "1.1.2"

[dependencies.binrw]
version = "0.11.1"
default-features = false

[dependencies.librs]
path = "../../libs/librs"

[dependencies.virtio]
path = "../virtio"
