[build]
target = "riscv64gc-unknown-none-elf"
rustflags = ["-Clink-arg=-Tkernel/link.ld"]

[target.riscv64gc-unknown-none-elf]
runner = "qemu-system-riscv64 -machine virt -cpu rv64 -bios none -smp 2 -m 128M -nographic -serial mon:stdio -kernel "
